vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        lightnovel_images:
            uri_prefix: /images/lightnovel
            upload_destination: '%kernel.project_dir%/public/images/lightnovel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer